-- Galaxy Fire Beats Marketplace
-- Run once in Supabase SQL Editor before accepting live beat payments.

create table if not exists public.beat_catalog (
  beat_id text primary key,
  title text not null,
  exclusive_sold boolean not null default false,
  sold_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.beat_sales (
  id bigint generated by default as identity primary key,
  order_reference text not null unique,
  beat_id text not null references public.beat_catalog(beat_id),
  beat_title text not null,
  license text not null check (license in ('Basic','Premium','Unlimited','Exclusive')),
  amount numeric(12,2) not null,
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  paystack_reference text not null unique,
  created_at timestamptz not null default now()
);

alter table public.beat_catalog enable row level security;
alter table public.beat_sales enable row level security;

create or replace function public.record_beat_sale(
  p_beat_id text,
  p_beat_title text,
  p_license text,
  p_amount numeric,
  p_customer_name text,
  p_customer_email text,
  p_customer_phone text,
  p_paystack_reference text
)
returns table(order_reference text, exclusive_sold boolean, created boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sold boolean;
  v_order text;
  v_created boolean := true;
begin
  select exclusive_sold into v_sold
  from public.beat_catalog
  where beat_id = p_beat_id
  for update;

  if not found then
    insert into public.beat_catalog (beat_id, title)
    values (p_beat_id, p_beat_title)
    returning exclusive_sold into v_sold;
  end if;

  select order_reference into v_order from public.beat_sales where paystack_reference = p_paystack_reference;
  if found then
    v_created := false;
    return query select v_order, v_sold, v_created;
  end if;

  if v_sold then
    raise exception 'Beat already sold exclusively';
  end if;

  v_order := 'GFS-BEAT-' || to_char(now(), 'YYMMDD') || '-' || upper(substr(md5(random()::text), 1, 6));

  insert into public.beat_sales (
    order_reference, beat_id, beat_title, license, amount,
    customer_name, customer_email, customer_phone, paystack_reference
  ) values (
    v_order, p_beat_id, p_beat_title, p_license, p_amount,
    p_customer_name, p_customer_email, p_customer_phone, p_paystack_reference
  )
  on conflict (paystack_reference) do update set paystack_reference = excluded.paystack_reference
  returning order_reference into v_order;

  if p_license = 'Exclusive' then
    update public.beat_catalog
    set exclusive_sold = true, sold_at = now(), title = p_beat_title
    where beat_id = p_beat_id;
    v_sold := true;
  end if;

  return query select v_order, v_sold, v_created;
end;
$$;

revoke all on function public.record_beat_sale(text,text,text,numeric,text,text,text,text) from public;

-- Centralized site-wide sale notification deduplication.
-- Run this addition in Supabase before enabling production email notifications.
create table if not exists public.sale_notifications (
  id bigint generated by default as identity primary key,
  paystack_reference text not null unique,
  sale_type text not null,
  created_at timestamptz not null default now()
);

alter table public.sale_notifications enable row level security;
revoke all on public.sale_notifications from public;
